version: "3.8"

name: parcial-docker-integrado

services:
  db:
    image: postgres:15-alpine
    container_name: parcial-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./api
    image: parcial-api:compose
    container_name: parcial-api
    ports:
      - "${API_PORT}:3000"
    environment:
      PORT: "3000"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net

networks:
  app_net:

volumes:
  db_data:
